#pragma once

#include <QCoreApplication>
#include <QMap>

namespace Configs {
class Profile;
}

static const QMap<QString, QString> CountryMap = {
    { QT_TRANSLATE_NOOP("CountryNames", "Afghanistan"), "AF" },
    { QT_TRANSLATE_NOOP("CountryNames", "Aland Islands"), "AX" },
    { QT_TRANSLATE_NOOP("CountryNames", "Albania"), "AL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Algeria"), "DZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "American Samoa"), "AS" },
    { QT_TRANSLATE_NOOP("CountryNames", "Andorra"), "AD" },
    { QT_TRANSLATE_NOOP("CountryNames", "Angola"), "AO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Anguilla"), "AI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Antarctica"), "AQ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Antigua And Barbuda"), "AG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Argentina"), "AR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Armenia"), "AM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Netherlands Antilles"), "AN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Aruba"), "AW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Australia"), "AU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Austria"), "AT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Azerbaijan"), "AZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bahamas"), "BS" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bahrain"), "BH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bangladesh"), "BD" },
    { QT_TRANSLATE_NOOP("CountryNames", "Barbados"), "BB" },
    { QT_TRANSLATE_NOOP("CountryNames", "Belarus"), "BY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Belgium"), "BE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Belize"), "BZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Benin"), "BJ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bermuda"), "BM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bhutan"), "BT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bolivia"), "BO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bosnia And Herzegovina"), "BA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Botswana"), "BW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bouvet Island"), "BV" },
    { QT_TRANSLATE_NOOP("CountryNames", "Brazil"), "BR" },
    { QT_TRANSLATE_NOOP("CountryNames", "British Indian Ocean Territory"), "IO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Brunei Darussalam"), "BN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Bulgaria"), "BG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Burkina Faso"), "BF" },
    { QT_TRANSLATE_NOOP("CountryNames", "Burundi"), "BI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cambodia"), "KH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cameroon"), "CM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Canada"), "CA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cape Verde"), "CV" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cayman Islands"), "KY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Central African Republic"), "CF" },
    { QT_TRANSLATE_NOOP("CountryNames", "Chad"), "TD" },
    { QT_TRANSLATE_NOOP("CountryNames", "Chile"), "CL" },
    { QT_TRANSLATE_NOOP("CountryNames", "China"), "CN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Christmas Island"), "CX" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cocos (Keeling) Islands"), "CC" },
    { QT_TRANSLATE_NOOP("CountryNames", "Colombia"), "CO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Comoros"), "KM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Congo"), "CG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Congo, Democratic Republic"), "CD" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cook Islands"), "CK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Costa Rica"), "CR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cote D\"Ivoire"), "CI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Croatia"), "HR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cuba"), "CU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Cyprus"), "CY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Czech Republic"), "CZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Denmark"), "DK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Djibouti"), "DJ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Dominica"), "DM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Dominican Republic"), "DO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Ecuador"), "EC" },
    { QT_TRANSLATE_NOOP("CountryNames", "Egypt"), "EG" },
    { QT_TRANSLATE_NOOP("CountryNames", "El Salvador"), "SV" },
    { QT_TRANSLATE_NOOP("CountryNames", "Equatorial Guinea"), "GQ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Eritrea"), "ER" },
    { QT_TRANSLATE_NOOP("CountryNames", "Estonia"), "EE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Ethiopia"), "ET" },
    { QT_TRANSLATE_NOOP("CountryNames", "Falkland Islands (Malvinas)"), "FK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Faroe Islands"), "FO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Fiji"), "FJ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Finland"), "FI" },
    { QT_TRANSLATE_NOOP("CountryNames", "France"), "FR" },
    { QT_TRANSLATE_NOOP("CountryNames", "French Guiana"), "GF" },
    { QT_TRANSLATE_NOOP("CountryNames", "French Polynesia"), "PF" },
    { QT_TRANSLATE_NOOP("CountryNames", "French Southern Territories"), "TF" },
    { QT_TRANSLATE_NOOP("CountryNames", "Gabon"), "GA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Gambia"), "GM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Georgia"), "GE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Germany"), "DE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Ghana"), "GH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Gibraltar"), "GI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Greece"), "GR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Greenland"), "GL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Grenada"), "GD" },
    { QT_TRANSLATE_NOOP("CountryNames", "Guadeloupe"), "GP" },
    { QT_TRANSLATE_NOOP("CountryNames", "Guam"), "GU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Guatemala"), "GT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Guernsey"), "GG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Guinea"), "GN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Guinea-Bissau"), "GW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Guyana"), "GY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Haiti"), "HT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Heard Island & Mcdonald Islands"), "HM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Holy See (Vatican City State)"), "VA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Honduras"), "HN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Hong Kong"), "HK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Hungary"), "HU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Iceland"), "IS" },
    { QT_TRANSLATE_NOOP("CountryNames", "India"), "IN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Indonesia"), "ID" },
    { QT_TRANSLATE_NOOP("CountryNames", "Iran, Islamic Republic Of"), "IR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Iraq"), "IQ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Ireland"), "IE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Isle Of Man"), "IM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Israel"), "IL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Italy"), "IT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Jamaica"), "JM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Japan"), "JP" },
    { QT_TRANSLATE_NOOP("CountryNames", "Jersey"), "JE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Jordan"), "JO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Kazakhstan"), "KZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Kenya"), "KE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Kiribati"), "KI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Korea"), "KR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Kuwait"), "KW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Kyrgyzstan"), "KG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Lao People\"s Democratic Republic"), "LA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Latvia"), "LV" },
    { QT_TRANSLATE_NOOP("CountryNames", "Lebanon"), "LB" },
    { QT_TRANSLATE_NOOP("CountryNames", "Lesotho"), "LS" },
    { QT_TRANSLATE_NOOP("CountryNames", "Liberia"), "LR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Libyan Arab Jamahiriya"), "LY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Liechtenstein"), "LI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Lithuania"), "LT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Luxembourg"), "LU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Macao"), "MO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Macedonia"), "MK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Madagascar"), "MG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Malawi"), "MW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Malaysia"), "MY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Maldives"), "MV" },
    { QT_TRANSLATE_NOOP("CountryNames", "Mali"), "ML" },
    { QT_TRANSLATE_NOOP("CountryNames", "Malta"), "MT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Marshall Islands"), "MH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Martinique"), "MQ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Mauritania"), "MR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Mauritius"), "MU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Mayotte"), "YT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Mexico"), "MX" },
    { QT_TRANSLATE_NOOP("CountryNames", "Micronesia, Federated States Of"), "FM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Moldova"), "MD" },
    { QT_TRANSLATE_NOOP("CountryNames", "Monaco"), "MC" },
    { QT_TRANSLATE_NOOP("CountryNames", "Mongolia"), "MN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Montenegro"), "ME" },
    { QT_TRANSLATE_NOOP("CountryNames", "Montserrat"), "MS" },
    { QT_TRANSLATE_NOOP("CountryNames", "Morocco"), "MA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Mozambique"), "MZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Myanmar"), "MM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Namibia"), "NA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Nauru"), "NR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Nepal"), "NP" },
    { QT_TRANSLATE_NOOP("CountryNames", "Netherlands"), "NL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Netherlands Antilles"), "AN" },
    { QT_TRANSLATE_NOOP("CountryNames", "New Caledonia"), "NC" },
    { QT_TRANSLATE_NOOP("CountryNames", "New Zealand"), "NZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Nicaragua"), "NI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Niger"), "NE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Nigeria"), "NG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Niue"), "NU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Norfolk Island"), "NF" },
    { QT_TRANSLATE_NOOP("CountryNames", "Northern Mariana Islands"), "MP" },
    { QT_TRANSLATE_NOOP("CountryNames", "Norway"), "NO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Oman"), "OM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Pakistan"), "PK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Palau"), "PW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Palestinian Territory, Occupied"), "PS" },
    { QT_TRANSLATE_NOOP("CountryNames", "Panama"), "PA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Papua New Guinea"), "PG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Paraguay"), "PY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Peru"), "PE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Philippines"), "PH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Pitcairn"), "PN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Poland"), "PL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Portugal"), "PT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Puerto Rico"), "PR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Qatar"), "QA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Reunion"), "RE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Romania"), "RO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Russian Federation"), "RU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Rwanda"), "RW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saint Barthelemy"), "BL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saint Helena"), "SH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saint Kitts And Nevis"), "KN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saint Lucia"), "LC" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saint Martin"), "MF" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saint Pierre And Miquelon"), "PM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saint Vincent And Grenadines"), "VC" },
    { QT_TRANSLATE_NOOP("CountryNames", "Samoa"), "WS" },
    { QT_TRANSLATE_NOOP("CountryNames", "San Marino"), "SM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Sao Tome And Principe"), "ST" },
    { QT_TRANSLATE_NOOP("CountryNames", "Saudi Arabia"), "SA" },
    { QT_TRANSLATE_NOOP("CountryNames", "Senegal"), "SN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Serbia"), "RS" },
    { QT_TRANSLATE_NOOP("CountryNames", "Seychelles"), "SC" },
    { QT_TRANSLATE_NOOP("CountryNames", "Sierra Leone"), "SL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Singapore"), "SG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Slovakia"), "SK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Slovenia"), "SI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Solomon Islands"), "SB" },
    { QT_TRANSLATE_NOOP("CountryNames", "Somalia"), "SO" },
    { QT_TRANSLATE_NOOP("CountryNames", "South Africa"), "ZA" },
    { QT_TRANSLATE_NOOP("CountryNames", "South Georgia And Sandwich Isl."), "GS" },
    { QT_TRANSLATE_NOOP("CountryNames", "Spain"), "ES" },
    { QT_TRANSLATE_NOOP("CountryNames", "Sri Lanka"), "LK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Sudan"), "SD" },
    { QT_TRANSLATE_NOOP("CountryNames", "Suriname"), "SR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Svalbard And Jan Mayen"), "SJ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Swaziland"), "SZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Sweden"), "SE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Switzerland"), "CH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Syrian Arab Republic"), "SY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Taiwan"), "TW" },
    { QT_TRANSLATE_NOOP("CountryNames", "Tajikistan"), "TJ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Tanzania"), "TZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Thailand"), "TH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Timor-Leste"), "TL" },
    { QT_TRANSLATE_NOOP("CountryNames", "Togo"), "TG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Tokelau"), "TK" },
    { QT_TRANSLATE_NOOP("CountryNames", "Tonga"), "TO" },
    { QT_TRANSLATE_NOOP("CountryNames", "Trinidad And Tobago"), "TT" },
    { QT_TRANSLATE_NOOP("CountryNames", "Tunisia"), "TN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Turkey"), "TR" },
    { QT_TRANSLATE_NOOP("CountryNames", "Turkmenistan"), "TM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Turks And Caicos Islands"), "TC" },
    { QT_TRANSLATE_NOOP("CountryNames", "Tuvalu"), "TV" },
    { QT_TRANSLATE_NOOP("CountryNames", "Uganda"), "UG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Ukraine"), "UA" },
    { QT_TRANSLATE_NOOP("CountryNames", "United Arab Emirates"), "AE" },
    { QT_TRANSLATE_NOOP("CountryNames", "United Kingdom"), "GB" },
    { QT_TRANSLATE_NOOP("CountryNames", "United States"), "US" },
    { QT_TRANSLATE_NOOP("CountryNames", "United States Outlying Islands"), "UM" },
    { QT_TRANSLATE_NOOP("CountryNames", "Uruguay"), "UY" },
    { QT_TRANSLATE_NOOP("CountryNames", "Uzbekistan"), "UZ" },
    { QT_TRANSLATE_NOOP("CountryNames", "Vanuatu"), "VU" },
    { QT_TRANSLATE_NOOP("CountryNames", "Venezuela"), "VE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Viet Nam"), "VN" },
    { QT_TRANSLATE_NOOP("CountryNames", "Virgin Islands, British"), "VG" },
    { QT_TRANSLATE_NOOP("CountryNames", "Virgin Islands, U.S."), "VI" },
    { QT_TRANSLATE_NOOP("CountryNames", "Wallis And Futuna"), "WF" },
    { QT_TRANSLATE_NOOP("CountryNames", "Western Sahara"), "EH" },
    { QT_TRANSLATE_NOOP("CountryNames", "Yemen"), "YE" },
    { QT_TRANSLATE_NOOP("CountryNames", "Zambia"), "ZM" },
};

QString CountryNameToCode(const QString& countryName);

QString CountryCodeToFlag(const QString& countryCode);

QString CountryCodeToName(const QString& countryCode);

QString countryCodeFromFlag(const QString& text);

QString effectiveCountryCode(const Configs::Profile& profile);
